<?php
/** @var \Codilar\Witch\Router $this */
?>
<style>
    body {
        background-color: #fafafa;
    }
    .error-template {
        padding: 2rem 1rem;
        margin-top: 5rem;
        text-align: center;
    }
    .error-actions {
        margin: 2rem 0;
    }
    .error-actions .btn {
        margin-right: 10px;
    }
</style>
<div class="404">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>Oops!</h1>
                <h2>404 Not Found</h2>
                <div class="error-details">
                    Sorry, an error has occured, Requested page not found!
                </div>
                <div class="error-actions">
                    <a href="/" class="btn btn-primary btn-lg">
                        <span class="glyphicon glyphicon-home"></span>
                        <span>Take Me Home</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
