<?php
/** @var \Codilar\Witch\Router $this */
?>
<style>
    .link {
        width: 100%;
        font-size: 2rem;
        margin-bottom: 1rem;
    }
</style>
<div class="row">
    <div class="col-md-6">
        <a href="/single-url" class="btn btn-info link">
            <span>Single URL</span>
        </a>
    </div>
    <div class="col-md-6">
        <a href="/csv" class="btn btn-info link">
            <span>CSV Upload</span>
        </a>
    </div>

</div>
