<?php
/** @var \Codilar\Witch\Router $this */
/** @var string $resolver */
?>
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous"
        >
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
                crossorigin="anonymous"
        ></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $this->getData('appName') ?> | Codilar</title>
    </head>
    <body>
        <header>
            <nav class="py-2 bg-light border-bottom">
                <div class="container d-flex flex-wrap">
                    <ul class="nav me-auto">
                        <li class="nav-item"><a href="#" class="nav-link link-dark px-2 active" aria-current="page">Home</a></li>
                        <li class="nav-item"><a href="#" class="nav-link link-dark px-2">About</a></li>
                    </ul>
                </div>
            </nav>
            <header class="py-3 mb-4 border-bottom">
                <div class="container d-flex flex-wrap justify-content-center">
                    <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto text-dark text-decoration-none">
                        <span class="fs-4"><?= $this->getData('appName') ?></span>
                        <span class="ms-2 fs-4">- <strong>W</strong>hat <strong>I</strong>s <strong>T</strong>he <strong>C</strong>ode <strong>H</strong>ere</span>
                    </a>
                </div>
            </header>
        </header>
        <div class="container">
            <?= $resolver ?>
        </div>
        <footer></footer>
    </body>
</html>
